//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.detroitlabs.nerdnite.api;

import android.app.Activity;
import android.content.Context;
import android.os.Handler;
import android.util.Log;
import android.view.View;
import com.googlecode.androidannotations.api.BackgroundExecutor;

public final class RestAPI_
    extends RestAPI
{

    private Context context_;
    private Handler handler_ = new Handler();

    private RestAPI_(Context context) {
        context_ = context;
        init_();
    }

    public void afterSetContentView_() {
        if (!(context_ instanceof Activity)) {
            return ;
        }
    }

    /**
     * You should check that context is an activity before calling this method
     * 
     */
    public View findViewById(int id) {
        Activity activity_ = ((Activity) context_);
        return activity_.findViewById(id);
    }

    @SuppressWarnings("all")
    private void init_() {
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
        ri = new RestInterface_();
    }

    public static RestAPI_ getInstance_(Context context) {
        return new RestAPI_(context);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

    @Override
    public void sendResponse(final Object response, final int requestCode, final RestAPICallback callback) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    RestAPI_.super.sendResponse(response, requestCode, callback);
                } catch (RuntimeException e) {
                    Log.e("RestAPI_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void sendError(final Exception error, final int requestCode, final RestAPICallback callback) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    RestAPI_.super.sendError(error, requestCode, callback);
                } catch (RuntimeException e) {
                    Log.e("RestAPI_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void getAllCities(final RestAPICallback callback, final int requestCode) {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    RestAPI_.super.getAllCities(callback, requestCode);
                } catch (RuntimeException e) {
                    Log.e("RestAPI_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

}
