//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.detroitlabs.nerdnite.api;

import com.detroitlabs.nerdnite.data.City;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.converter.json.GsonHttpMessageConverter;
import org.springframework.web.client.RestTemplate;

public class RestInterface_
    implements RestInterface
{

    private RestTemplate restTemplate;
    private String rootUrl;

    public RestInterface_() {
        restTemplate = new RestTemplate();
        restTemplate.getMessageConverters().add(new GsonHttpMessageConverter());
        rootUrl = "http://nn-server-dev.herokuapp.com/";
    }

    @Override
    public City[] getCities() {
        HttpHeaders httpHeaders = new HttpHeaders();
        HttpEntity<Object> requestEntity = new HttpEntity<Object>(httpHeaders);
        return restTemplate.exchange(rootUrl.concat("/cities"), HttpMethod.GET, requestEntity, City[].class).getBody();
    }

}
